ENT.Type			= "anim"
ENT.Base			= "wtib_tiberiumbase"
ENT.PrintName		= "Green Tiberium"
ENT.Author			= "kevkev/Warrior xXx"
ENT.Contact			= ""
ENT.Purpose			= ""
ENT.Instructions	= ""
ENT.Spawnable		= true
ENT.AdminSpawnable	= true
ENT.Category		= "Tiberium"
ENT.IsTiberium		= true
