ENT.Type			= "anim"
ENT.Base			= "wtib_tiberiumbase"
ENT.PrintName		= "Green Tiberium"
ENT.Author			= "kevkev/Warrior xXx"
ENT.Contact			= ""
ENT.Purpose			= ""
ENT.Instructions	= ""
ENT.Spawnable		= true
ENT.AdminSpawnable	= true
ENT.Category		= "Tiberium"
ENT.IsTiberium		= true

ENT.TiberiumDraimOnReproduction = 1200
ENT.MinReprodutionTibRequired = 1500
ENT.RemoveOnNoTiberium = true
ENT.MinTiberiumGain = 15
ENT.MaxTiberiumGain = 50
ENT.ShouldReproduce = true
ENT.ReproduceDelay = 60
ENT.MaxTiberium = 2000
ENT.TiberiumAdd = true
ENT.DynLight = true
ENT.Gas = true
ENT.r = 0
ENT.g = 255
ENT.b = 0
