ENT.Type			= "anim"
ENT.PrintName		= "Medium Refined Tiberium Storage"
ENT.WireDebugName	= "Medium Refined Tiberium Storage"
ENT.Author			= "kevkev/Warrior xXx"
ENT.Contact			= ""
ENT.Purpose			= ""
ENT.Instructions	= ""
ENT.Spawnable		= true
ENT.AdminSpawnable	= true
ENT.Category		= "Tiberium"
