ENT.Type			= "anim"
ENT.Base			= "wtib_tiberiumparentbase"
ENT.PrintName		= "Blue Tiberium Parent"
ENT.Author			= "kevkev/Warrior xXx"
ENT.Contact			= ""
ENT.Purpose			= ""
ENT.Instructions	= ""
ENT.Spawnable		= false
ENT.AdminSpawnable	= true
ENT.Category		= "Tiberium"
ENT.IsTiberium		= true
ENT.CanBeHarvested	= false
ENT.NoPhysicsPickup	= true

ENT.ReproduceDelay				= 10
ENT.TiberiumClass				= "wtib_bluetiberium"
ENT.DynLight					= true
ENT.Class						= "wtib_bluetiberiumparent"
ENT.r							= 0
ENT.g							= 0
ENT.b							= 255
ENT.a							= 150
