ENT.Type			= "anim"
ENT.Base			= "wtib_tiberiumbase"
ENT.PrintName		= "Tiberium infected prop"
ENT.Author			= "kevkev/Warrior xXx"
ENT.Contact			= ""
ENT.Purpose			= ""
ENT.Instructions	= ""
ENT.Spawnable		= false
ENT.AdminSpawnable	= false
ENT.Category		= "Tiberium"
ENT.IsTiberium		= true

ENT.TiberiumDraimOnReproduction = 0
ENT.MinReprodutionTibRequired = 1000
ENT.MinTiberiumGain = 5
ENT.MaxTiberiumGain = 20
ENT.ReproduceDelay = 0
ENT.MaxTiberium = 500
ENT.TiberiumAdd = true
ENT.Reproduce = false
ENT.DynLight = false
--ENT.Divider = 2
ENT.Gas = false
ENT.r = 0
ENT.g = 255
ENT.b = 30
