ENT.Type			= "anim"
ENT.PrintName		= "Medium Tiberium Harvester"
ENT.WireDebugName	= ENT.PrintName
ENT.Author			= "kevkev/Warrior xXx"
ENT.Contact			= ""
ENT.Purpose			= ""
ENT.Instructions	= ""
ENT.Spawnable		= false
ENT.AdminSpawnable	= false
ENT.Category		= "Tiberium"
