ENT.Type			= "anim"
ENT.PrintName		= "Medium Tiberium Chemicals Storage"
ENT.WireDebugName	= ENT.PrintName
ENT.Author			= "kevkev/Warrior xXx"
ENT.Contact			= ""
ENT.Purpose			= ""
ENT.Instructions	= ""
ENT.Spawnable		= true
ENT.AdminSpawnable	= true
ENT.Category		= "Tiberium"
