ENT.Type			= "anim"
ENT.PrintName		= "Tiberium shard"
ENT.Author			= "kevkev/Warrior xXx"
ENT.Contact			= ""
ENT.Purpose			= ""
ENT.Instructions	= ""
ENT.Spawnable		= false
ENT.AdminSpawnable	= false
ENT.NoPhysicsPickup	= true
