ENT.Type			= "anim"
ENT.Base			= "wtib_tiberiumbase"
ENT.PrintName		= "Blue Tiberium"
ENT.Author			= "kevkev/Warrior xXx"
ENT.Contact			= ""
ENT.Purpose			= ""
ENT.Instructions	= ""
ENT.Spawnable		= true
ENT.AdminSpawnable	= true
ENT.Category		= "Tiberium"
ENT.IsTiberium		= true

ENT.TiberiumDraimOnReproduction = 2000
ENT.MinReprodutionTibRequired = 2300
ENT.MinTiberiumGain = 20
ENT.MaxTiberiumGain = 60
ENT.ReproduceDelay = 70
ENT.MaxTiberium = 3000
ENT.TiberiumAdd = true
ENT.Reproduce = true
ENT.DynLight = true
--ENT.Divider = 12
ENT.Gas = false
ENT.r = 0
ENT.g = 0
ENT.b = 255
