ENT.Type			= "anim"
ENT.Base			= "wtib_tiberiumbase"
ENT.PrintName		= "Blue Tiberium"
ENT.Author			= "kevkev/Warrior xXx"
ENT.Contact			= ""
ENT.Purpose			= ""
ENT.Instructions	= ""
ENT.Spawnable		= true
ENT.AdminSpawnable	= true
ENT.Category		= "Tiberium"
ENT.IsTiberium		= true
ENT.CanBeHarvested	= true
ENT.NoPhysicsPickup	= true

ENT.TiberiumDraimOnReproduction	= 2000
ENT.MinReprodutionTibRequired	= 2300
ENT.RemoveOnNoTiberium			= true
ENT.IgnoreExpBurDamage			= false
ENT.ReproductionRate			= 10
ENT.MinTiberiumGain				= 20
ENT.MaxTiberiumGain				= 60
ENT.ShouldReproduce				= true
ENT.ReproduceDelay				= 70
ENT.MaxTiberium					= 3000
ENT.TiberiumAdd					= true
ENT.DynLight					= true
ENT.Class						= "wtib_bluetiberium"
ENT.Gas							= true
ENT.r							= 0
ENT.g							= 0
ENT.b							= 255
