
SWEP.Base					= "wtib_weapon_base"
SWEP.Author					= "kevkev/Warrior xXx"
SWEP.Contact				= ""
SWEP.Purpose				= "Shooting tiberium shards."
SWEP.Instructions			= "Leftclick or rightclick to shoot shards."
SWEP.Spawnable				= true
SWEP.AdminSpawnable			= true
SWEP.ViewModel				= "models/weapons/v_smg1.mdl"
SWEP.WorldModel				= "models/weapons/w_smg1.mdl"
SWEP.ViewModelFlip			= false
SWEP.Weight					= 5
SWEP.AutoSwitchTo			= false
SWEP.AutoSwitchFrom			= false
SWEP.PrintName				= "Tiberium shard launcher"	
SWEP.Slot					= 4
SWEP.SlotPos				= 5
SWEP.DrawAmmo				= true
SWEP.DrawCrosshair			= true
SWEP.Category				= "Tiberium"

SWEP.ClipSize				= 30
SWEP.Bullets				= 90
SWEP.ReloadTime				= 2
SWEP.Ammo					= "basebullets"
SWEP.SecAmmo				= "basesecondary"
SWEP.HoldType				= "pistol"
SWEP.PrimeDelay				= 0.1
SWEP.SecClipSize			= 10
SWEP.SecDelay				= 2